variable "external_id" {
  description = "(DO NOT CHANGE) External ID generated by Opsima to provide secure access to your AWS account."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", var.external_id))
    error_message = "external_id must be a UUID, e.g. 12345678-1234-1234-1234-123456789012."
  }
}

variable "opsima_principal" {
  description = "(DO NOT CHANGE) Opsima AWS account ID used to access your AWS account."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9]{12}$", var.opsima_principal))
    error_message = "opsima_principal must be a 12-digit AWS account ID."
  }
}

variable "create_cur_bucket" {
  description = "(DO NOT CHANGE) Whether to create the Cost & Usage Report (CUR) S3 bucket."
  type        = bool
  default     = true
}

variable "customer_short_id" {
  description = "(DO NOT CHANGE) Short ID generated by Opsima for the customer."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9a-fA-F]{10}$", var.customer_short_id))
    error_message = "customer_short_id must be a 10-character hex string."
  }
}

variable "organization_id" {
  description = "(DO NOT CHANGE) Customer AWS Organization ID."
  type        = string

  validation {
    condition     = can(regex("^o-[a-z0-9]{10}$", var.organization_id))
    error_message = "organization_id must look like o-xxxxxxxxxx."
  }
}

variable "organization_root_id" {
  description = "(DO NOT CHANGE) Customer AWS Organization Root ID."
  type        = string

  validation {
    condition     = can(regex("^r-[a-z0-9]{4,32}$", var.organization_root_id))
    error_message = "organization_root_id must look like r-xxxx."
  }
}

variable "role_name" {
  description = "Name of the IAM role assumed by Opsima."
  type        = string
  default     = "OpsimaRemoteAccessRole"
}

variable "tags" {
  description = "Extra tags merged into every taggable resource this module creates."
  type        = map(string)
  default     = {}
}
