variable "external_id" {
  description = "(DO NOT CHANGE) External ID generated by Opsima to provide secure access to your AWS account."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", var.external_id))
    error_message = "external_id must be a UUID, e.g. 12345678-1234-1234-1234-123456789012."
  }
}

variable "opsima_principal" {
  description = "(DO NOT CHANGE) Opsima AWS account ID used to access your AWS account."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9]{12}$", var.opsima_principal))
    error_message = "opsima_principal must be a 12-digit AWS account ID."
  }
}

variable "create_cur_bucket" {
  description = "(DO NOT CHANGE) Whether to create the Cost & Usage Report (CUR) S3 bucket."
  type        = bool
  default     = true
}

variable "create_opsima_organizational_unit" {
  description = "(DO NOT CHANGE) Whether to create the Opsima Organizational Unit. Only takes effect when opsima_organizational_unit_id is left empty."
  type        = bool
  default     = true
}

variable "customer_short_id" {
  description = "(DO NOT CHANGE) Short ID generated by Opsima for the customer."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9a-fA-F]{10}$", var.customer_short_id))
    error_message = "customer_short_id must be a 10-character hex string."
  }
}

variable "organization_id" {
  description = "(DO NOT CHANGE) Customer AWS Organization ID."
  type        = string

  validation {
    condition     = can(regex("^o-[a-z0-9]{10}$", var.organization_id))
    error_message = "organization_id must look like o-xxxxxxxxxx."
  }
}

variable "organization_root_id" {
  description = "(DO NOT CHANGE) Customer AWS Organization Root ID."
  type        = string

  validation {
    condition     = can(regex("^r-[a-z0-9]{4,32}$", var.organization_root_id))
    error_message = "organization_root_id must look like r-xxxx."
  }
}

variable "opsima_organizational_unit_id" {
  description = "(DO NOT CHANGE) Organizational Unit ID where Opsima-managed accounts will be placed. Leave empty to have this module create one automatically (see create_opsima_organizational_unit)."
  type        = string
  default     = ""

  validation {
    condition     = var.opsima_organizational_unit_id == "" || can(regex("^ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}$", var.opsima_organizational_unit_id))
    error_message = "opsima_organizational_unit_id must be empty or look like ou-xxxx-xxxxxxxx."
  }
}

variable "opsima_invoice_unit_arn" {
  description = "(DO NOT CHANGE) Invoice Unit ARN where Opsima-managed accounts will be placed. Automatically created by Opsima if left empty."
  type        = string
  default     = ""

  validation {
    condition     = var.opsima_invoice_unit_arn == "" || can(regex("^arn:aws:invoicing::\\d{12}:invoice-unit/[A-Za-z0-9-]+$", var.opsima_invoice_unit_arn))
    error_message = "opsima_invoice_unit_arn must be empty or a valid invoicing invoice-unit ARN."
  }
}

# HANDSHAKE SECTION

variable "enable_opsima_handshake" {
  description = <<-EOT
    Whether to notify Opsima's onboarding backend once the role/policy are in
    place. Runs the original Custom::OpsimaHandshake as a one-resource nested
    CloudFormation stack (see README); needs cloudformation:*Stack permissions
    on the apply credentials. Set to false to onboard from Opsima's UI instead.
  EOT
  type        = bool
  default     = true
}

variable "opsima_handshake_sns_topic_arn" {
  description = "SNS topic ARN Opsima's onboarding backend listens on for the setup handshake."
  type        = string
  default     = "arn:aws:sns:eu-west-1:539247457822:OpsimaLimitedAccessRoleSetup"
}

variable "cloudformation_stack_version" {
  description = "Value reported to Opsima as CloudFormationStackVersion in the handshake payload (kept for compatibility with Opsima's backend)."
  type        = string
  default     = "10"
}

variable "role_name" {
  description = "Name of the IAM role assumed by Opsima."
  type        = string
  default     = "OpsimaRemoteAccessRole"
}

variable "tags" {
  description = "Extra tags merged into every taggable resource this module creates."
  type        = map(string)
  default     = {}
}
